CREATE TABLE "City" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "country" varchar(255) NOT NULL,
  "population" integer,
  "region" varchar(255),
  "latitude" decimal(9,6) NOT NULL,
  "longitude" decimal(9,6) NOT NULL,
  "elevation" decimal(8,2)
);

CREATE TABLE "WeatherCondition" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "condition_name" varchar(255) NOT NULL,
  "description" text,
  "icon_url" varchar(255)
);

CREATE TABLE "Forecast" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "city_id" integer,
  "weather_condition_id" integer,
  "temperature" decimal(5,2) NOT NULL,
  "feels_like" decimal(5,2),
  "humidity" decimal(5,2),
  "wind_speed" decimal(5,2),
  "precipitation" decimal(5,2),
  "timestamp" timestamp NOT NULL
);

CREATE TABLE "historic_weather" (
  "historic_weather_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "city_id" integer,
  "weather_condition_id" integer,
  "temperature" decimal(5,2),
  "humidity" decimal(5,2),
  "wind_speed" decimal(5,2),
  "precipitation" decimal(5,2),
  "timestamp" timestamp NOT NULL
);

CREATE TABLE "educational_links" (
  "link_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "city_id" integer,
  "historic_weather_id" integer,
  "link_url" varchar(255) NOT NULL,
  "description" text
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "username" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "city_id" integer,
  "city_location" varchar(255),
  "post_count" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "comments" (
  "comment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" integer,
  "content" text,
  "historic_weather_id" integer,
  "timestamp" timestamp DEFAULT (current_timestamp)
);

ALTER TABLE "Forecast" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("id");

ALTER TABLE "Forecast" ADD FOREIGN KEY ("weather_condition_id") REFERENCES "WeatherCondition" ("id");

ALTER TABLE "historic_weather" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("id");

ALTER TABLE "historic_weather" ADD FOREIGN KEY ("weather_condition_id") REFERENCES "WeatherCondition" ("id");

ALTER TABLE "educational_links" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("id");

ALTER TABLE "educational_links" ADD FOREIGN KEY ("historic_weather_id") REFERENCES "historic_weather" ("historic_weather_id");

ALTER TABLE "users" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "comments" ADD FOREIGN KEY ("historic_weather_id") REFERENCES "historic_weather" ("historic_weather_id");
